package marketdigest

import (
	"fmt"
	"sort"
	"strings"
	"time"

	"stock-portfolio/internal/divergencealerts"
	"stock-portfolio/internal/technicalalerts"
)

type tickerGroup struct {
	Ticker      string
	Name        string
	Category    string
	LastClose   float64
	Divergences []divergencealerts.Alert
	Technical   []technicalalerts.Alert
}

type timeframeSignals struct {
	Divergences []divergencealerts.Alert
	Technical   []technicalalerts.Alert
}

type multiTickerGroup struct {
	Ticker          string
	Name            string
	Category        string
	LastClose       float64
	Daily           timeframeSignals
	Weekly          timeframeSignals
	DailyChange     float64
	HasDailyChange  bool
	WeeklyChange    float64
	HasWeeklyChange bool
}

type topPick struct {
	ticker  string
	name    string
	score   int
	signals []string
}

func GenerateReport(divergences []divergencealerts.Alert, technical []technicalalerts.Alert, timeframe string, emaThreshold float64) string {
	return GenerateReportWithCategoryOrder(divergences, technical, timeframe, emaThreshold, nil)
}

func GenerateReportWithCategoryOrder(divergences []divergencealerts.Alert, technical []technicalalerts.Alert, timeframe string, emaThreshold float64, categoryOrder map[string]int) string {
	sortDivergences(divergences)
	sortTechnical(technical)
	groups := groupByTicker(divergences, technical)
	categories := groupByCategory(groups, categoryOrder)

	var sb strings.Builder
	writeHeader(&sb)
	sb.WriteString(fmt.Sprintf("<h2>Market Signal Digest (%s) — %s</h2>\n", strings.ToUpper(timeframe), time.Now().Format("02/01/2006")))
	sb.WriteString(fmt.Sprintf("<p class=\"muted\">%d categories · %d tickers · %d RSI divergences · %d technical signals · EMA proximity threshold %.2f%%</p>\n", len(categories), len(groups), len(divergences), len(technical), emaThreshold))

	writeTopSection(&sb, groups)

	for _, category := range categories {
		writeCategorySection(&sb, category)
	}

	sb.WriteString(`<p class="footer">Generated by stock-checker.</p>`)
	sb.WriteString("</body>\n</html>")
	return sb.String()
}

func sortDivergences(divergences []divergencealerts.Alert) {
	sort.SliceStable(divergences, func(i, j int) bool {
		if divergences[i].Divergence.Kind == divergences[j].Divergence.Kind {
			return divergences[i].Stock.Ticker < divergences[j].Stock.Ticker
		}
		return divergences[i].Divergence.Kind == "bearish"
	})
}

func sortTechnical(technical []technicalalerts.Alert) {
	sort.SliceStable(technical, func(i, j int) bool {
		if technical[i].Kind == technical[j].Kind {
			if technical[i].Stock.Ticker == technical[j].Stock.Ticker {
				return technical[i].Period < technical[j].Period
			}
			return technical[i].Stock.Ticker < technical[j].Stock.Ticker
		}
		return signalRank(technical[i].Kind) < signalRank(technical[j].Kind)
	})
}

func writeHeader(sb *strings.Builder) {
	sb.WriteString(`<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<style>
  body { font-family: Arial, sans-serif; max-width: 960px; margin: 0 auto; padding: 20px; background: #f5f5f5; color: #24303d; }
  h2 { color: #24303d; border-bottom: 2px solid #34495e; padding-bottom: 8px; }
  h3 { margin-top: 26px; margin-bottom: 10px; color: #24303d; }
  .cat-count { color:#777; font-size:12px; font-weight: normal; }
  table { width: 100%; border-collapse: collapse; background: white; border-radius: 8px; overflow: hidden; box-shadow: 0 1px 4px rgba(0,0,0,0.1); }
  .signal-table { table-layout: fixed; }
  th { background: #17202a; color: white; padding: 10px 12px; text-align: left; font-size: 13px; }
  td { padding: 10px 12px; border-bottom: 1px solid #eee; font-size: 14px; vertical-align: top; overflow-wrap: anywhere; word-break: normal; }
  tr:last-child td { border-bottom: none; }
  .stock-col { width: 36%; }
  .change-col { width: 9%; }
  .signals-col { width: 23%; }
  .single-stock-col { width: 36%; }
  .single-signals-col { width: 64%; }
  .ticker { font-weight: bold; white-space: nowrap; }
  .category, .muted { color:#777; font-size:12px; }
  .number { text-align: right; white-space: nowrap; }
  .signal-list { margin: 0; padding-left: 18px; }
  .signal-list li { margin: 2px 0 6px; }
  .empty { color: #aaa; font-size: 12px; }
  .bearish, .below { color: #e74c3c; font-weight: bold; }
  .bullish, .above { color: #27ae60; font-weight: bold; }
  .watch { color: #9b6a1d; font-weight: bold; }
  .neutral { color: #2d8f6f; font-weight: bold; }
  .footer { margin-top: 16px; font-size: 12px; color: #999; }
</style>
</head>
<body>
`)
}

func GenerateMultiTimeframeReport(dailyDivergences []divergencealerts.Alert, dailyTechnical []technicalalerts.Alert, weeklyDivergences []divergencealerts.Alert, weeklyTechnical []technicalalerts.Alert, dailyEMAThreshold float64, weeklyEMAThreshold float64, categoryOrder map[string]int) string {
	sortDivergences(dailyDivergences)
	sortDivergences(weeklyDivergences)
	sortTechnical(dailyTechnical)
	sortTechnical(weeklyTechnical)

	groups := groupByTickerMulti(dailyDivergences, dailyTechnical, weeklyDivergences, weeklyTechnical)
	categories := groupMultiByCategory(groups, categoryOrder)

	var sb strings.Builder
	writeHeader(&sb)
	sb.WriteString(fmt.Sprintf("<h2>Market Signal Digest (DAILY + WEEKLY) — %s</h2>\n", time.Now().Format("02/01/2006")))
	sb.WriteString(fmt.Sprintf("<p class=\"muted\">%d categories · %d tickers · daily: %d divergences / %d technical · weekly: %d divergences / %d technical · EMA thresholds %.2f%% / %.2f%%</p>\n",
		len(categories),
		len(groups),
		len(dailyDivergences),
		len(dailyTechnical),
		len(weeklyDivergences),
		len(weeklyTechnical),
		dailyEMAThreshold,
		weeklyEMAThreshold,
	))

	writeTopSectionMulti(&sb, groups)
	for _, category := range categories {
		writeCategorySectionMulti(&sb, category)
	}

	sb.WriteString(`<p class="footer">Generated by stock-checker.</p>`)
	sb.WriteString("</body>\n</html>")
	return sb.String()
}

func groupByTicker(divergences []divergencealerts.Alert, technical []technicalalerts.Alert) []tickerGroup {
	byTicker := make(map[string]*tickerGroup)
	for _, alert := range divergences {
		g := ensureGroup(byTicker, alert.Stock.Ticker, alert.Stock.Name, alert.Stock.Category)
		g.Divergences = append(g.Divergences, alert)
		g.LastClose = alert.LastClose
	}
	for _, alert := range technical {
		g := ensureGroup(byTicker, alert.Stock.Ticker, alert.Stock.Name, alert.Stock.Category)
		g.Technical = append(g.Technical, alert)
		if alert.LastClose > 0 {
			g.LastClose = alert.LastClose
		}
	}
	groups := make([]tickerGroup, 0, len(byTicker))
	for _, g := range byTicker {
		groups = append(groups, *g)
	}
	sort.SliceStable(groups, func(i, j int) bool {
		left := len(groups[i].Divergences) + len(groups[i].Technical)
		right := len(groups[j].Divergences) + len(groups[j].Technical)
		if left == right {
			return groups[i].Ticker < groups[j].Ticker
		}
		return left > right
	})
	return groups
}

func groupByTickerMulti(dailyDivergences []divergencealerts.Alert, dailyTechnical []technicalalerts.Alert, weeklyDivergences []divergencealerts.Alert, weeklyTechnical []technicalalerts.Alert) []multiTickerGroup {
	byTicker := make(map[string]*multiTickerGroup)
	for _, alert := range dailyDivergences {
		g := ensureMultiGroup(byTicker, alert.Stock.Ticker, alert.Stock.Name, alert.Stock.Category)
		g.Daily.Divergences = append(g.Daily.Divergences, alert)
		g.LastClose = alert.LastClose
		g.DailyChange = alert.ChangePercent
		g.HasDailyChange = true
	}
	for _, alert := range dailyTechnical {
		g := ensureMultiGroup(byTicker, alert.Stock.Ticker, alert.Stock.Name, alert.Stock.Category)
		g.Daily.Technical = append(g.Daily.Technical, alert)
		if alert.LastClose > 0 {
			g.LastClose = alert.LastClose
		}
		g.DailyChange = alert.ChangePercent
		g.HasDailyChange = true
	}
	for _, alert := range weeklyDivergences {
		g := ensureMultiGroup(byTicker, alert.Stock.Ticker, alert.Stock.Name, alert.Stock.Category)
		g.Weekly.Divergences = append(g.Weekly.Divergences, alert)
		if g.LastClose == 0 {
			g.LastClose = alert.LastClose
		}
		g.WeeklyChange = alert.ChangePercent
		g.HasWeeklyChange = true
	}
	for _, alert := range weeklyTechnical {
		g := ensureMultiGroup(byTicker, alert.Stock.Ticker, alert.Stock.Name, alert.Stock.Category)
		g.Weekly.Technical = append(g.Weekly.Technical, alert)
		if g.LastClose == 0 && alert.LastClose > 0 {
			g.LastClose = alert.LastClose
		}
		g.WeeklyChange = alert.ChangePercent
		g.HasWeeklyChange = true
	}
	groups := make([]multiTickerGroup, 0, len(byTicker))
	for _, g := range byTicker {
		groups = append(groups, *g)
	}
	sort.SliceStable(groups, func(i, j int) bool {
		left := multiSignalCount(groups[i])
		right := multiSignalCount(groups[j])
		if left == right {
			return groups[i].Ticker < groups[j].Ticker
		}
		return left > right
	})
	return groups
}

func ensureMultiGroup(groups map[string]*multiTickerGroup, ticker, name, category string) *multiTickerGroup {
	g, ok := groups[ticker]
	if ok {
		return g
	}
	g = &multiTickerGroup{Ticker: ticker, Name: name, Category: category}
	groups[ticker] = g
	return g
}

func multiSignalCount(group multiTickerGroup) int {
	return len(group.Daily.Divergences) + len(group.Daily.Technical) + len(group.Weekly.Divergences) + len(group.Weekly.Technical)
}

func groupMultiByCategory(groups []multiTickerGroup, categoryOrder map[string]int) []multiCategoryGroup {
	if categoryOrder == nil {
		categoryOrder = map[string]int{}
	}
	byCategory := make(map[string][]multiTickerGroup)
	for _, group := range groups {
		category := group.Category
		if category == "" {
			category = "Uncategorized"
		}
		byCategory[category] = append(byCategory[category], group)
	}
	categories := make([]multiCategoryGroup, 0, len(byCategory))
	for category, tickers := range byCategory {
		categories = append(categories, multiCategoryGroup{Name: category, Tickers: tickers})
	}
	sort.SliceStable(categories, func(i, j int) bool {
		leftOrder, leftOK := categoryOrder[categories[i].Name]
		rightOrder, rightOK := categoryOrder[categories[j].Name]
		if leftOK && rightOK && leftOrder != rightOrder {
			return leftOrder < rightOrder
		}
		if leftOK != rightOK {
			return leftOK
		}
		return categories[i].Name < categories[j].Name
	})
	return categories
}

type multiCategoryGroup struct {
	Name    string
	Tickers []multiTickerGroup
}

func topByBias(groups []tickerGroup, bias string, limit int) []topPick {
	var picks []topPick
	for _, group := range groups {
		pick := topPick{ticker: group.Ticker, name: group.Name}
		for _, alert := range group.Divergences {
			if alert.Divergence.Kind != bias {
				continue
			}
			pick.score++
			pick.signals = append(pick.signals, strings.ToUpper(alert.Divergence.Kind)+" RSI divergence")
		}
		for _, alert := range group.Technical {
			if alert.Bias != bias {
				continue
			}
			pick.score++
			pick.signals = append(pick.signals, alert.Label)
		}
		if pick.score > 0 {
			picks = append(picks, pick)
		}
	}
	sort.SliceStable(picks, func(i, j int) bool {
		if picks[i].score == picks[j].score {
			return picks[i].ticker < picks[j].ticker
		}
		return picks[i].score > picks[j].score
	})
	if len(picks) > limit {
		return picks[:limit]
	}
	return picks
}

func topByBiasMulti(groups []multiTickerGroup, bias string, limit int) []topPick {
	var picks []topPick
	for _, group := range groups {
		pick := topPick{ticker: group.Ticker, name: group.Name}
		dailyScore := appendBiasSignals(&pick, group.Daily, bias, "D")
		weeklyScore := appendBiasSignals(&pick, group.Weekly, bias, "W")
		pick.score = dailyScore + weeklyScore
		if dailyScore > 0 && weeklyScore > 0 {
			pick.score += 2
			pick.signals = append(pick.signals, "daily+weekly alignment")
		}
		if pick.score > 0 {
			picks = append(picks, pick)
		}
	}
	sort.SliceStable(picks, func(i, j int) bool {
		if picks[i].score == picks[j].score {
			return picks[i].ticker < picks[j].ticker
		}
		return picks[i].score > picks[j].score
	})
	if len(picks) > limit {
		return picks[:limit]
	}
	return picks
}

func appendBiasSignals(pick *topPick, signals timeframeSignals, bias string, prefix string) int {
	score := 0
	for _, alert := range signals.Divergences {
		if alert.Divergence.Kind != bias {
			continue
		}
		score++
		pick.signals = append(pick.signals, prefix+": "+strings.ToUpper(alert.Divergence.Kind)+" RSI divergence")
	}
	for _, alert := range signals.Technical {
		if alert.Bias != bias {
			continue
		}
		score++
		pick.signals = append(pick.signals, prefix+": "+alert.Label)
	}
	return score
}

type categoryGroup struct {
	Name    string
	Tickers []tickerGroup
}

func groupByCategory(groups []tickerGroup, categoryOrder map[string]int) []categoryGroup {
	if categoryOrder == nil {
		categoryOrder = map[string]int{}
	}
	byCategory := make(map[string][]tickerGroup)
	for _, group := range groups {
		category := group.Category
		if category == "" {
			category = "Uncategorized"
		}
		byCategory[category] = append(byCategory[category], group)
	}
	categories := make([]categoryGroup, 0, len(byCategory))
	for category, tickers := range byCategory {
		categories = append(categories, categoryGroup{Name: category, Tickers: tickers})
	}
	sort.SliceStable(categories, func(i, j int) bool {
		leftOrder, leftOK := categoryOrder[categories[i].Name]
		rightOrder, rightOK := categoryOrder[categories[j].Name]
		if leftOK && rightOK && leftOrder != rightOrder {
			return leftOrder < rightOrder
		}
		if leftOK != rightOK {
			return leftOK
		}
		return categories[i].Name < categories[j].Name
	})
	return categories
}

func ensureGroup(groups map[string]*tickerGroup, ticker, name, category string) *tickerGroup {
	g, ok := groups[ticker]
	if ok {
		return g
	}
	g = &tickerGroup{Ticker: ticker, Name: name, Category: category}
	groups[ticker] = g
	return g
}

func writeTopSection(sb *strings.Builder, groups []tickerGroup) {
	bullish := topByBias(groups, "bullish", 3)
	bearish := topByBias(groups, "bearish", 3)
	if len(bullish) == 0 && len(bearish) == 0 {
		return
	}
	sb.WriteString("<h3>Top Signals</h3>\n")
	sb.WriteString("<table>\n")
	sb.WriteString("  <tr><th>Top bullish</th><th>Top bearish</th></tr>\n")
	sb.WriteString("  <tr><td>")
	writeTopList(sb, bullish, "bullish")
	sb.WriteString("</td><td>")
	writeTopList(sb, bearish, "bearish")
	sb.WriteString("</td></tr>\n")
	sb.WriteString("</table>\n")
}

func writeTopSectionMulti(sb *strings.Builder, groups []multiTickerGroup) {
	bullish := topByBiasMulti(groups, "bullish", 3)
	bearish := topByBiasMulti(groups, "bearish", 3)
	if len(bullish) == 0 && len(bearish) == 0 {
		return
	}
	sb.WriteString("<h3>Top Signals</h3>\n")
	sb.WriteString("<table>\n")
	sb.WriteString("  <tr><th>Top bullish</th><th>Top bearish</th></tr>\n")
	sb.WriteString("  <tr><td>")
	writeTopList(sb, bullish, "bullish")
	sb.WriteString("</td><td>")
	writeTopList(sb, bearish, "bearish")
	sb.WriteString("</td></tr>\n")
	sb.WriteString("</table>\n")
}

func writeTopList(sb *strings.Builder, picks []topPick, className string) {
	if len(picks) == 0 {
		sb.WriteString(`<span class="muted">None</span>`)
		return
	}
	sb.WriteString(`<ol class="signal-list">`)
	for _, pick := range picks {
		sb.WriteString(fmt.Sprintf(
			`<li><span class="%s">%s</span> <span class="muted">%d signals</span><br><span class="muted">%s</span></li>`,
			className,
			pick.ticker,
			pick.score,
			strings.Join(pick.signals, ", "),
		))
	}
	sb.WriteString(`</ol>`)
}

func writeCategorySection(sb *strings.Builder, category categoryGroup) {
	sb.WriteString(fmt.Sprintf("<h3>%s <span class=\"cat-count\">%d tickers</span></h3>\n", category.Name, len(category.Tickers)))
	sb.WriteString("<table class=\"signal-table\">\n")
	sb.WriteString("  <tr><th class=\"single-stock-col\">Stock</th><th class=\"single-signals-col\">Signals</th></tr>\n")
	for _, group := range category.Tickers {
		signals := formatSignals(group)
		sb.WriteString(fmt.Sprintf(
			`  <tr>
    <td class="single-stock-col"><span class="ticker">%s</span> <span class="muted">- %s</span></td>
    <td class="single-signals-col">%s</td>
  </tr>
`,
			group.Ticker,
			group.Name,
			signals,
		))
	}
	sb.WriteString("</table>\n")
}

func writeCategorySectionMulti(sb *strings.Builder, category multiCategoryGroup) {
	sb.WriteString(fmt.Sprintf("<h3>%s <span class=\"cat-count\">%d tickers</span></h3>\n", category.Name, len(category.Tickers)))
	sb.WriteString("<table class=\"signal-table\">\n")
	sb.WriteString("  <tr><th class=\"stock-col\">Stock</th><th class=\"change-col\">Daily change</th><th class=\"signals-col\">Daily signals</th><th class=\"change-col\">Weekly change</th><th class=\"signals-col\">Weekly signals</th></tr>\n")
	for _, group := range category.Tickers {
		daily := formatTimeframeSignals(group.Daily)
		weekly := formatTimeframeSignals(group.Weekly)
		sb.WriteString(fmt.Sprintf(
			`  <tr>
    <td class="stock-col"><span class="ticker">%s</span> <span class="muted">- %s</span></td>
    <td class="number change-col">%s</td>
    <td class="signals-col">%s</td>
    <td class="number change-col">%s</td>
    <td class="signals-col">%s</td>
  </tr>
`,
			group.Ticker,
			group.Name,
			formatChange(group.DailyChange, group.HasDailyChange),
			daily,
			formatChange(group.WeeklyChange, group.HasWeeklyChange),
			weekly,
		))
	}
	sb.WriteString("</table>\n")
}

func formatTimeframeSignals(signals timeframeSignals) string {
	return formatSignals(tickerGroup{Divergences: signals.Divergences, Technical: signals.Technical})
}

func formatSignals(group tickerGroup) string {
	if len(group.Divergences) == 0 && len(group.Technical) == 0 {
		return `<span class="empty">-</span>`
	}
	parts := make([]string, 0, len(group.Divergences)+len(group.Technical))
	for _, alert := range group.Divergences {
		div := alert.Divergence
		parts = append(parts, fmt.Sprintf(
			`<span class="%s">%s RSI divergence</span> <span class="muted">%s → %s</span>`,
			div.Kind,
			strings.ToUpper(div.Kind),
			formatDate(div.FromTime),
			formatDate(div.ToTime),
		))
	}
	for _, alert := range group.Technical {
		biasClass := alert.Bias
		if biasClass == "" {
			biasClass = "neutral"
		}
		parts = append(parts, fmt.Sprintf(
			`<span class="%s">%s</span>`,
			biasClass,
			alert.Label,
		))
	}
	return strings.Join(parts, ` <span class="muted">·</span> `)
}

func formatChange(value float64, ok bool) string {
	if !ok {
		return `<span class="empty">-</span>`
	}
	className := "above"
	if value < 0 {
		className = "below"
	}
	return fmt.Sprintf(`<span class="%s">%+.2f%%</span>`, className, value)
}

func signalRank(kind technicalalerts.Kind) int {
	switch kind {
	case technicalalerts.EMAReclaim, technicalalerts.EMALoss:
		return 10
	case technicalalerts.Breakout, technicalalerts.Breakdown:
		return 20
	case technicalalerts.RSIRegimeUp, technicalalerts.RSIRegimeDn:
		return 30
	case technicalalerts.MACDBullish, technicalalerts.MACDBearish:
		return 40
	case technicalalerts.EMAProximity:
		return 90
	default:
		return 100
	}
}

func formatDate(ts int64) string {
	if ts <= 0 {
		return ""
	}
	return time.Unix(ts, 0).Format("02 Jan 2006")
}
