package marketdigest

import (
	"fmt"
	"sort"
	"strings"
	"time"

	"stock-portfolio/internal/divergencealerts"
	"stock-portfolio/internal/technicalalerts"
)

type tickerGroup struct {
	InPortfolio *bool
	Ticker      string
	Name        string
	Category    string
	LastClose   float64
	Divergences []divergencealerts.Alert
	Technical   []technicalalerts.Alert
}

type timeframeSignals struct {
	Divergences []divergencealerts.Alert
	Technical   []technicalalerts.Alert
}

type multiTickerGroup struct {
	InPortfolio     *bool
	Ticker          string
	Name            string
	Category        string
	LastClose       float64
	Daily           timeframeSignals
	Weekly          timeframeSignals
	DailyChange     float64
	HasDailyChange  bool
	WeeklyChange    float64
	HasWeeklyChange bool
}

type ChangeSummary struct {
	DailyChange     float64
	HasDailyChange  bool
	WeeklyChange    float64
	HasWeeklyChange bool
}

func GenerateReport(divergences []divergencealerts.Alert, technical []technicalalerts.Alert, timeframe string, emaThreshold float64) string {
	return GenerateReportWithCategoryOrder(divergences, technical, timeframe, emaThreshold, nil)
}

func GenerateReportWithCategoryOrder(divergences []divergencealerts.Alert, technical []technicalalerts.Alert, timeframe string, emaThreshold float64, categoryOrder map[string]int, options ...RankingOptions) string {
	sortDivergences(divergences)
	sortTechnical(technical)
	groups := groupByTicker(divergences, technical)
	categories := groupByCategory(groups, categoryOrder)

	var sb strings.Builder
	writeHeader(&sb)
	sb.WriteString(fmt.Sprintf("<h2>Market Signal Digest - %s</h2>\n", time.Now().Format("02/01/2006")))
	sb.WriteString(fmt.Sprintf("<p class=\"muted\">%d categories · %d tickers · %d RSI divergences · %d technical signals · EMA proximity threshold %.2f%%</p>\n", len(categories), len(groups), len(divergences), len(technical), emaThreshold))

	writeTopSection(&sb, groups, timeframe, rankingOptions(options))

	for _, category := range categories {
		writeCategorySection(&sb, category)
	}

	sb.WriteString(`<p class="footer">Generated by stock-checker.</p>`)
	sb.WriteString("</body>\n</html>")
	return sb.String()
}

func sortDivergences(divergences []divergencealerts.Alert) {
	sort.SliceStable(divergences, func(i, j int) bool {
		if divergences[i].Divergence.Kind == divergences[j].Divergence.Kind {
			return divergences[i].Stock.Ticker < divergences[j].Stock.Ticker
		}
		return divergences[i].Divergence.Kind == "bearish"
	})
}

func sortTechnical(technical []technicalalerts.Alert) {
	sort.SliceStable(technical, func(i, j int) bool {
		if technical[i].Kind == technical[j].Kind {
			if technical[i].Stock.Ticker == technical[j].Stock.Ticker {
				return technical[i].Period < technical[j].Period
			}
			return technical[i].Stock.Ticker < technical[j].Stock.Ticker
		}
		return signalRank(technical[i].Kind) < signalRank(technical[j].Kind)
	})
}

func writeHeader(sb *strings.Builder) {
	sb.WriteString(`<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
  body { font-family: Arial, sans-serif; max-width: 960px; margin: 0 auto; padding: 20px; background: #f5f5f5; color: #24303d; }
  h2 { color: #24303d; border-bottom: 2px solid #34495e; padding-bottom: 8px; }
  h3 { margin-top: 26px; margin-bottom: 10px; color: #24303d; }
  .cat-count { color:#777; font-size:12px; font-weight: normal; }
  table { width: 100%; border-collapse: collapse; background: white; border-radius: 8px; overflow: hidden; box-shadow: 0 1px 4px rgba(0,0,0,0.1); }
  .signal-table { table-layout: fixed; }
  th { background: #17202a; color: white; padding: 10px 12px; text-align: left; font-size: 13px; }
  td { padding: 10px 12px; border-bottom: 1px solid #eee; font-size: 14px; vertical-align: top; overflow-wrap: anywhere; word-break: normal; }
  tr:last-child td { border-bottom: none; }
  .stock-col { width: 34%; }
  .period-col { width: 33%; }
  .single-stock-col { width: 36%; }
  .single-signals-col { width: 64%; }
  .ticker { font-weight: bold; white-space: nowrap; }
  .category, .muted { color:#777; font-size:12px; }
  .number { text-align: right; white-space: nowrap; }
  .signal-list { margin: 0; padding-left: 18px; }
  .signal-list li { margin: 2px 0 6px; }
  .empty { color: #aaa; font-size: 12px; }
  .bearish, .below { color: #e74c3c; font-weight: bold; }
  .bullish, .above { color: #27ae60; font-weight: bold; }
  .watch { color: #9b6a1d; font-weight: bold; }
  .neutral { color: #2d8f6f; font-weight: bold; }
  .footer { margin-top: 16px; font-size: 12px; color: #999; }
  .top-picks { table-layout: fixed; }
  .financial-table { table-layout: fixed; }
  .financial-table th:first-child { width: 20%; }
  .financial-table td { font-size: 12px; line-height: 1.6; }
  .top-picks th, .top-picks td { width: 50%; overflow-wrap: anywhere; }
  .pick-action { display: block; font-weight: bold; margin: 4px 0; }
  .pick-reasons { font-size: 12px; margin: 4px 0 10px; padding-left: 16px; }
  @media (max-width: 600px) { body { padding: 12px; } .top-picks th, .top-picks td { padding: 8px; } }
</style>
</head>
<body>
`)
}

func GenerateMultiTimeframeReport(dailyDivergences []divergencealerts.Alert, dailyTechnical []technicalalerts.Alert, weeklyDivergences []divergencealerts.Alert, weeklyTechnical []technicalalerts.Alert, dailyEMAThreshold float64, weeklyEMAThreshold float64, categoryOrder map[string]int) string {
	return GenerateMultiTimeframeReportWithChanges(dailyDivergences, dailyTechnical, weeklyDivergences, weeklyTechnical, dailyEMAThreshold, weeklyEMAThreshold, categoryOrder, nil)
}

func GenerateMultiTimeframeReportWithChanges(dailyDivergences []divergencealerts.Alert, dailyTechnical []technicalalerts.Alert, weeklyDivergences []divergencealerts.Alert, weeklyTechnical []technicalalerts.Alert, dailyEMAThreshold float64, weeklyEMAThreshold float64, categoryOrder map[string]int, changes map[string]ChangeSummary, options ...RankingOptions) string {
	sortDivergences(dailyDivergences)
	sortDivergences(weeklyDivergences)
	sortTechnical(dailyTechnical)
	sortTechnical(weeklyTechnical)

	groups := groupByTickerMulti(dailyDivergences, dailyTechnical, weeklyDivergences, weeklyTechnical)
	applyChanges(groups, changes)
	categories := groupMultiByCategory(groups, categoryOrder)

	var sb strings.Builder
	writeHeader(&sb)
	sb.WriteString(fmt.Sprintf("<h2>Market Signal Digest - %s</h2>\n", time.Now().Format("02/01/2006")))
	sb.WriteString(fmt.Sprintf("<p class=\"muted\">%d categories · %d tickers · daily: %d divergences / %d technical · weekly: %d divergences / %d technical · EMA thresholds %.2f%% / %.2f%%</p>\n",
		len(categories),
		len(groups),
		len(dailyDivergences),
		len(dailyTechnical),
		len(weeklyDivergences),
		len(weeklyTechnical),
		dailyEMAThreshold,
		weeklyEMAThreshold,
	))

	writeTopSectionMulti(&sb, groups, rankingOptions(options))
	for _, category := range categories {
		writeCategorySectionMulti(&sb, category)
	}

	sb.WriteString(`<p class="footer">Generated by stock-checker.</p>`)
	sb.WriteString("</body>\n</html>")
	return sb.String()
}

func applyChanges(groups []multiTickerGroup, changes map[string]ChangeSummary) {
	if len(changes) == 0 {
		return
	}
	for i := range groups {
		change, ok := changes[groups[i].Ticker]
		if !ok {
			continue
		}
		if change.HasDailyChange {
			groups[i].DailyChange = change.DailyChange
			groups[i].HasDailyChange = true
		}
		if change.HasWeeklyChange {
			groups[i].WeeklyChange = change.WeeklyChange
			groups[i].HasWeeklyChange = true
		}
	}
}

func groupByTicker(divergences []divergencealerts.Alert, technical []technicalalerts.Alert) []tickerGroup {
	byTicker := make(map[string]*tickerGroup)
	for _, alert := range divergences {
		g := ensureGroup(byTicker, alert.Stock.Ticker, alert.Stock.Name, alert.Stock.Category)
		g.InPortfolio = alert.Stock.InPortfolio
		g.Divergences = append(g.Divergences, alert)
		g.LastClose = alert.LastClose
	}
	for _, alert := range technical {
		g := ensureGroup(byTicker, alert.Stock.Ticker, alert.Stock.Name, alert.Stock.Category)
		g.InPortfolio = alert.Stock.InPortfolio
		g.Technical = append(g.Technical, alert)
		if alert.LastClose > 0 {
			g.LastClose = alert.LastClose
		}
	}
	groups := make([]tickerGroup, 0, len(byTicker))
	for _, g := range byTicker {
		groups = append(groups, *g)
	}
	sort.SliceStable(groups, func(i, j int) bool {
		left := len(groups[i].Divergences) + len(groups[i].Technical)
		right := len(groups[j].Divergences) + len(groups[j].Technical)
		if left == right {
			return groups[i].Ticker < groups[j].Ticker
		}
		return left > right
	})
	return groups
}

func groupByTickerMulti(dailyDivergences []divergencealerts.Alert, dailyTechnical []technicalalerts.Alert, weeklyDivergences []divergencealerts.Alert, weeklyTechnical []technicalalerts.Alert) []multiTickerGroup {
	byTicker := make(map[string]*multiTickerGroup)
	for _, alert := range dailyDivergences {
		g := ensureMultiGroup(byTicker, alert.Stock.Ticker, alert.Stock.Name, alert.Stock.Category)
		g.InPortfolio = alert.Stock.InPortfolio
		g.Daily.Divergences = append(g.Daily.Divergences, alert)
		g.LastClose = alert.LastClose
		g.DailyChange = alert.ChangePercent
		g.HasDailyChange = true
	}
	for _, alert := range dailyTechnical {
		g := ensureMultiGroup(byTicker, alert.Stock.Ticker, alert.Stock.Name, alert.Stock.Category)
		g.InPortfolio = alert.Stock.InPortfolio
		g.Daily.Technical = append(g.Daily.Technical, alert)
		if alert.LastClose > 0 {
			g.LastClose = alert.LastClose
		}
		g.DailyChange = alert.ChangePercent
		g.HasDailyChange = true
	}
	for _, alert := range weeklyDivergences {
		g := ensureMultiGroup(byTicker, alert.Stock.Ticker, alert.Stock.Name, alert.Stock.Category)
		g.InPortfolio = alert.Stock.InPortfolio
		g.Weekly.Divergences = append(g.Weekly.Divergences, alert)
		if g.LastClose == 0 {
			g.LastClose = alert.LastClose
		}
		g.WeeklyChange = alert.ChangePercent
		g.HasWeeklyChange = true
	}
	for _, alert := range weeklyTechnical {
		g := ensureMultiGroup(byTicker, alert.Stock.Ticker, alert.Stock.Name, alert.Stock.Category)
		g.InPortfolio = alert.Stock.InPortfolio
		g.Weekly.Technical = append(g.Weekly.Technical, alert)
		if g.LastClose == 0 && alert.LastClose > 0 {
			g.LastClose = alert.LastClose
		}
		g.WeeklyChange = alert.ChangePercent
		g.HasWeeklyChange = true
	}
	groups := make([]multiTickerGroup, 0, len(byTicker))
	for _, g := range byTicker {
		groups = append(groups, *g)
	}
	sort.SliceStable(groups, func(i, j int) bool {
		left := multiSignalCount(groups[i])
		right := multiSignalCount(groups[j])
		if left == right {
			return groups[i].Ticker < groups[j].Ticker
		}
		return left > right
	})
	return groups
}

func ensureMultiGroup(groups map[string]*multiTickerGroup, ticker, name, category string) *multiTickerGroup {
	g, ok := groups[ticker]
	if ok {
		return g
	}
	g = &multiTickerGroup{Ticker: ticker, Name: name, Category: category}
	groups[ticker] = g
	return g
}

func multiSignalCount(group multiTickerGroup) int {
	return len(group.Daily.Divergences) + len(group.Daily.Technical) + len(group.Weekly.Divergences) + len(group.Weekly.Technical)
}

func groupMultiByCategory(groups []multiTickerGroup, categoryOrder map[string]int) []multiCategoryGroup {
	if categoryOrder == nil {
		categoryOrder = map[string]int{}
	}
	byCategory := make(map[string][]multiTickerGroup)
	for _, group := range groups {
		category := group.Category
		if category == "" {
			category = "Uncategorized"
		}
		byCategory[category] = append(byCategory[category], group)
	}
	categories := make([]multiCategoryGroup, 0, len(byCategory))
	for category, tickers := range byCategory {
		categories = append(categories, multiCategoryGroup{Name: category, Tickers: tickers})
	}
	sort.SliceStable(categories, func(i, j int) bool {
		leftOrder, leftOK := categoryOrder[categories[i].Name]
		rightOrder, rightOK := categoryOrder[categories[j].Name]
		if leftOK && rightOK && leftOrder != rightOrder {
			return leftOrder < rightOrder
		}
		if leftOK != rightOK {
			return leftOK
		}
		return categories[i].Name < categories[j].Name
	})
	return categories
}

type multiCategoryGroup struct {
	Name    string
	Tickers []multiTickerGroup
}

type categoryGroup struct {
	Name    string
	Tickers []tickerGroup
}

func groupByCategory(groups []tickerGroup, categoryOrder map[string]int) []categoryGroup {
	if categoryOrder == nil {
		categoryOrder = map[string]int{}
	}
	byCategory := make(map[string][]tickerGroup)
	for _, group := range groups {
		category := group.Category
		if category == "" {
			category = "Uncategorized"
		}
		byCategory[category] = append(byCategory[category], group)
	}
	categories := make([]categoryGroup, 0, len(byCategory))
	for category, tickers := range byCategory {
		categories = append(categories, categoryGroup{Name: category, Tickers: tickers})
	}
	sort.SliceStable(categories, func(i, j int) bool {
		leftOrder, leftOK := categoryOrder[categories[i].Name]
		rightOrder, rightOK := categoryOrder[categories[j].Name]
		if leftOK && rightOK && leftOrder != rightOrder {
			return leftOrder < rightOrder
		}
		if leftOK != rightOK {
			return leftOK
		}
		return categories[i].Name < categories[j].Name
	})
	return categories
}

func ensureGroup(groups map[string]*tickerGroup, ticker, name, category string) *tickerGroup {
	g, ok := groups[ticker]
	if ok {
		return g
	}
	g = &tickerGroup{Ticker: ticker, Name: name, Category: category}
	groups[ticker] = g
	return g
}

func writeCategorySection(sb *strings.Builder, category categoryGroup) {
	sb.WriteString(fmt.Sprintf("<h3>%s <span class=\"cat-count\">%d tickers</span></h3>\n", category.Name, len(category.Tickers)))
	sb.WriteString("<table class=\"signal-table\">\n")
	sb.WriteString("  <tr><th class=\"single-stock-col\">Stock</th><th class=\"single-signals-col\">Signals</th></tr>\n")
	for _, group := range category.Tickers {
		signals := formatSignals(group)
		sb.WriteString(fmt.Sprintf(
			`  <tr>
    <td class="single-stock-col"><span class="ticker">%s</span> <span class="muted">- %s</span></td>
    <td class="single-signals-col">%s</td>
  </tr>
`,
			group.Ticker,
			group.Name,
			signals,
		))
	}
	sb.WriteString("</table>\n")
}

func writeCategorySectionMulti(sb *strings.Builder, category multiCategoryGroup) {
	sb.WriteString(fmt.Sprintf("<h3>%s <span class=\"cat-count\">%d tickers</span></h3>\n", category.Name, len(category.Tickers)))
	sb.WriteString("<table class=\"signal-table\">\n")
	sb.WriteString("  <tr><th class=\"stock-col\">Stock</th><th class=\"period-col\">Daily</th><th class=\"period-col\">Weekly</th></tr>\n")
	for _, group := range category.Tickers {
		daily := formatPeriodCell(group.DailyChange, group.HasDailyChange, group.Daily)
		weekly := formatPeriodCell(group.WeeklyChange, group.HasWeeklyChange, group.Weekly)
		sb.WriteString(fmt.Sprintf(
			`  <tr>
    <td class="stock-col"><span class="ticker">%s</span> <span class="muted">- %s</span></td>
    <td class="period-col">%s</td>
    <td class="period-col">%s</td>
  </tr>
`,
			group.Ticker,
			group.Name,
			daily,
			weekly,
		))
	}
	sb.WriteString("</table>\n")
}

func formatPeriodCell(change float64, hasChange bool, signals timeframeSignals) string {
	return formatChange(change, hasChange) + `<br>` + formatTimeframeSignals(signals)
}

func formatTimeframeSignals(signals timeframeSignals) string {
	return formatSignals(tickerGroup{Divergences: signals.Divergences, Technical: signals.Technical})
}

func formatSignals(group tickerGroup) string {
	if len(group.Divergences) == 0 && len(group.Technical) == 0 {
		return `<span class="empty">-</span>`
	}
	parts := make([]string, 0, len(group.Divergences)+len(group.Technical))
	for _, alert := range group.Divergences {
		div := alert.Divergence
		parts = append(parts, fmt.Sprintf(
			`<span class="%s">%s RSI divergence</span> <span class="muted">%s → %s</span>`,
			div.Kind,
			strings.ToUpper(div.Kind),
			formatDate(div.FromTime),
			formatDate(div.ToTime),
		))
	}
	for _, alert := range group.Technical {
		biasClass := alert.Bias
		if biasClass == "" {
			biasClass = "neutral"
		}
		parts = append(parts, fmt.Sprintf(
			`<span class="%s">%s</span>`,
			biasClass,
			alert.Label,
		))
	}
	return strings.Join(parts, ` <span class="muted">·</span> `)
}

func formatChange(value float64, ok bool) string {
	if !ok {
		return `<span class="empty">-</span>`
	}
	className := "above"
	if value < 0 {
		className = "below"
	}
	return fmt.Sprintf(`<span class="%s">%+.2f%%</span>`, className, value)
}

func signalRank(kind technicalalerts.Kind) int {
	switch kind {
	case technicalalerts.EMAReclaim, technicalalerts.EMALoss:
		return 10
	case technicalalerts.Breakout, technicalalerts.Breakdown:
		return 20
	case technicalalerts.RSIRegimeUp, technicalalerts.RSIRegimeDn:
		return 30
	case technicalalerts.MACDBullish, technicalalerts.MACDBearish:
		return 40
	case technicalalerts.EMAProximity:
		return 90
	default:
		return 100
	}
}

func formatDate(ts int64) string {
	if ts <= 0 {
		return ""
	}
	return time.Unix(ts, 0).Format("02 Jan 2006")
}
