package marketdigest

import (
	"fmt"
	"sort"
	"strings"
	"time"

	"stock-portfolio/internal/divergencealerts"
	"stock-portfolio/internal/technicalalerts"
)

type tickerGroup struct {
	Ticker      string
	Name        string
	Category    string
	LastClose   float64
	Divergences []divergencealerts.Alert
	Technical   []technicalalerts.Alert
}

func GenerateReport(divergences []divergencealerts.Alert, technical []technicalalerts.Alert, timeframe string, emaThreshold float64) string {
	sort.SliceStable(divergences, func(i, j int) bool {
		if divergences[i].Divergence.Kind == divergences[j].Divergence.Kind {
			return divergences[i].Stock.Ticker < divergences[j].Stock.Ticker
		}
		return divergences[i].Divergence.Kind == "bearish"
	})
	sort.SliceStable(technical, func(i, j int) bool {
		if technical[i].Kind == technical[j].Kind {
			if technical[i].Stock.Ticker == technical[j].Stock.Ticker {
				return technical[i].Period < technical[j].Period
			}
			return technical[i].Stock.Ticker < technical[j].Stock.Ticker
		}
		return signalRank(technical[i].Kind) < signalRank(technical[j].Kind)
	})
	groups := groupByTicker(divergences, technical)

	var sb strings.Builder
	sb.WriteString(`<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<style>
  body { font-family: Arial, sans-serif; max-width: 960px; margin: 0 auto; padding: 20px; background: #f5f5f5; color: #24303d; }
  h2 { color: #24303d; border-bottom: 2px solid #34495e; padding-bottom: 8px; }
  h3 { margin-top: 26px; margin-bottom: 10px; color: #24303d; }
  table { width: 100%; border-collapse: collapse; background: white; border-radius: 8px; overflow: hidden; box-shadow: 0 1px 4px rgba(0,0,0,0.1); }
  th { background: #17202a; color: white; padding: 10px 12px; text-align: left; font-size: 13px; }
  td { padding: 10px 12px; border-bottom: 1px solid #eee; font-size: 14px; vertical-align: top; }
  tr:last-child td { border-bottom: none; }
  .ticker { font-weight: bold; white-space: nowrap; }
  .category, .muted { color:#777; font-size:12px; }
  .number { text-align: right; white-space: nowrap; }
  .signal-list { margin: 0; padding-left: 18px; }
  .signal-list li { margin: 2px 0 6px; }
  .bearish, .below { color: #e74c3c; font-weight: bold; }
  .bullish, .above { color: #27ae60; font-weight: bold; }
  .watch { color: #9b6a1d; font-weight: bold; }
  .neutral { color: #2d8f6f; font-weight: bold; }
  .footer { margin-top: 16px; font-size: 12px; color: #999; }
</style>
</head>
<body>
`)
	sb.WriteString(fmt.Sprintf("<h2>Market Signal Digest (%s) — %s</h2>\n", strings.ToUpper(timeframe), time.Now().Format("02/01/2006")))
	sb.WriteString(fmt.Sprintf("<p class=\"muted\">%d tickers · %d RSI divergences · %d technical signals · EMA proximity threshold %.2f%%</p>\n", len(groups), len(divergences), len(technical), emaThreshold))

	if len(groups) > 0 {
		writeTickerSection(&sb, groups)
	}

	sb.WriteString(`<p class="footer">Generated by stock-checker.</p>`)
	sb.WriteString("</body>\n</html>")
	return sb.String()
}

func groupByTicker(divergences []divergencealerts.Alert, technical []technicalalerts.Alert) []tickerGroup {
	byTicker := make(map[string]*tickerGroup)
	for _, alert := range divergences {
		g := ensureGroup(byTicker, alert.Stock.Ticker, alert.Stock.Name, alert.Stock.Category)
		g.Divergences = append(g.Divergences, alert)
		g.LastClose = alert.LastClose
	}
	for _, alert := range technical {
		g := ensureGroup(byTicker, alert.Stock.Ticker, alert.Stock.Name, alert.Stock.Category)
		g.Technical = append(g.Technical, alert)
		if alert.LastClose > 0 {
			g.LastClose = alert.LastClose
		}
	}
	groups := make([]tickerGroup, 0, len(byTicker))
	for _, g := range byTicker {
		groups = append(groups, *g)
	}
	sort.SliceStable(groups, func(i, j int) bool {
		left := len(groups[i].Divergences) + len(groups[i].Technical)
		right := len(groups[j].Divergences) + len(groups[j].Technical)
		if left == right {
			return groups[i].Ticker < groups[j].Ticker
		}
		return left > right
	})
	return groups
}

func ensureGroup(groups map[string]*tickerGroup, ticker, name, category string) *tickerGroup {
	g, ok := groups[ticker]
	if ok {
		return g
	}
	g = &tickerGroup{Ticker: ticker, Name: name, Category: category}
	groups[ticker] = g
	return g
}

func writeTickerSection(sb *strings.Builder, groups []tickerGroup) {
	sb.WriteString("<h3>Signals by Ticker</h3>\n")
	sb.WriteString("<table>\n")
	sb.WriteString("  <tr><th>Stock</th><th>Signals</th><th>Last close</th></tr>\n")
	for _, group := range groups {
		signals := formatSignals(group)
		sb.WriteString(fmt.Sprintf(
			`  <tr>
    <td><span class="ticker">%s</span><br><span class="muted">%s</span><br><span class="category">%s</span></td>
    <td>%s</td>
    <td class="number">%.2f</td>
  </tr>
`,
			group.Ticker,
			group.Name,
			group.Category,
			signals,
			group.LastClose,
		))
	}
	sb.WriteString("</table>\n")
}

func formatSignals(group tickerGroup) string {
	var sb strings.Builder
	sb.WriteString(`<ul class="signal-list">`)
	for _, alert := range group.Divergences {
		div := alert.Divergence
		sb.WriteString(fmt.Sprintf(
			`<li><span class="%s">%s RSI divergence</span><br><span class="muted">%s → %s · price %.2f → %.2f · RSI %.1f → %.1f</span></li>`,
			div.Kind,
			strings.ToUpper(div.Kind),
			formatDate(div.FromTime),
			formatDate(div.ToTime),
			div.FromPrice,
			div.ToPrice,
			div.FromRSI,
			div.ToRSI,
		))
	}
	for _, alert := range group.Technical {
		biasClass := alert.Bias
		if biasClass == "" {
			biasClass = "neutral"
		}
		sb.WriteString(fmt.Sprintf(
			`<li><span class="%s">%s</span><br><span class="muted">%s · level %.2f · distance %+.2f%%</span></li>`,
			biasClass,
			alert.Label,
			alert.Detail,
			alert.Level,
			alert.DistancePercent,
		))
	}
	sb.WriteString(`</ul>`)
	return sb.String()
}

func signalRank(kind technicalalerts.Kind) int {
	switch kind {
	case technicalalerts.EMAReclaim, technicalalerts.EMALoss:
		return 10
	case technicalalerts.Breakout, technicalalerts.Breakdown:
		return 20
	case technicalalerts.RSIRegimeUp, technicalalerts.RSIRegimeDn:
		return 30
	case technicalalerts.MACDBullish, technicalalerts.MACDBearish:
		return 40
	case technicalalerts.EMAProximity:
		return 90
	default:
		return 100
	}
}

func formatDate(ts int64) string {
	if ts <= 0 {
		return ""
	}
	return time.Unix(ts, 0).Format("02 Jan 2006")
}
