package alerts

import (
	"fmt"
	"math"
	"sort"
	"strings"
	"time"
)

// grouped holds one row per ticker with all crossed thresholds merged.
type grouped struct {
	Alert
	thresholds []float64
}

// groupByTicker merges multiple alerts for the same ticker into one row,
// collecting all crossed thresholds. Preserves original order (first occurrence).
func groupByTicker(alerts []Alert) []grouped {
	seen := make(map[string]int) // ticker -> index in result
	var result []grouped
	for _, a := range alerts {
		if idx, ok := seen[a.Stock.Ticker]; ok {
			result[idx].thresholds = append(result[idx].thresholds, a.Threshold)
		} else {
			seen[a.Stock.Ticker] = len(result)
			result = append(result, grouped{Alert: a, thresholds: []float64{a.Threshold}})
		}
	}
	return result
}

func sortByAbsoluteChange(alerts []grouped) {
	sort.SliceStable(alerts, func(i, j int) bool {
		left := math.Abs(alerts[i].ChangePercent)
		right := math.Abs(alerts[j].ChangePercent)
		if left == right {
			return alerts[i].Stock.Ticker < alerts[j].Stock.Ticker
		}
		return left > right
	})
}

// GenerateReport produces a simple HTML email body for the triggered alerts.
// Stocks that crossed multiple thresholds in the same run appear as a single row.
func GenerateReport(alerts []Alert) string {
	var sb strings.Builder

	sb.WriteString(`<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<style>
  body { font-family: Arial, sans-serif; max-width: 760px; margin: 0 auto; padding: 20px; background: #f5f5f5; color: #24303d; }
  h2 { color: #333; border-bottom: 2px solid #e74c3c; padding-bottom: 8px; }
  table { width: 100%; border-collapse: collapse; background: white; border-radius: 8px; overflow: hidden; box-shadow: 0 1px 4px rgba(0,0,0,0.1); }
  th { background: #2c3e50; color: white; padding: 10px 14px; text-align: left; font-size: 13px; }
  td { padding: 10px 14px; border-bottom: 1px solid #eee; font-size: 14px; }
  tr:last-child td { border-bottom: none; }
  .category { color:#888; font-size:12px; }
  .ticker { font-weight: bold; white-space: nowrap; }
  .number { text-align: right; white-space: nowrap; }
  .up   { color: #27ae60; font-weight: bold; }
  .down { color: #e74c3c; font-weight: bold; }
  .footer { margin-top: 16px; font-size: 12px; color: #999; }
</style>
</head>
<body>
`)

	sb.WriteString(fmt.Sprintf("<h2>🚨 Price Alerts — %s</h2>\n", time.Now().Format("02/01/2006")))
	sb.WriteString("<table>\n")
	sb.WriteString("  <tr><th>Stock</th><th>Ticker</th><th>Category</th><th>Open</th><th>Current</th><th>Change</th></tr>\n")

	groupedAlerts := groupByTicker(alerts)
	sortByAbsoluteChange(groupedAlerts)

	for _, g := range groupedAlerts {
		changeClass := "up"
		changeSign := "+"
		if g.ChangePercent < 0 {
			changeClass = "down"
			changeSign = ""
		}
		sb.WriteString(fmt.Sprintf(
			`  <tr>
    <td>%s</td>
    <td class="ticker">%s</td>
    <td class="category">%s</td>
    <td class="number">%.2f</td>
    <td class="number">%.2f</td>
    <td class="number %s">%s%.2f%%</td>
  </tr>
`,
			g.Stock.Name, g.Stock.Ticker,
			g.Stock.Category,
			g.OpenPrice, g.CurrentPrice,
			changeClass, changeSign, g.ChangePercent,
		))
	}

	sb.WriteString("</table>\n")
	sb.WriteString(`<p class="footer">Generated by stock-checker</p>`)
	sb.WriteString("</body>\n</html>")

	return sb.String()
}

// EmailSubject builds a concise subject line summarising the alerts.
func EmailSubject(alerts []Alert) string {
	if len(alerts) == 0 {
		return ""
	}
	parts := make([]string, 0, len(alerts))
	for _, a := range alerts {
		sign := "+"
		if a.ChangePercent < 0 {
			sign = ""
		}
		parts = append(parts, fmt.Sprintf("%s %s%.1f%%", a.Stock.Ticker, sign, a.ChangePercent))
	}
	return fmt.Sprintf("🚨 Price Alert: %s", strings.Join(parts, ", "))
}
