package emaalerts

import (
	"fmt"
	"math"
	"sort"
	"strings"
	"time"
)

func GenerateReport(alerts []Alert, timeframe Timeframe, thresholdPercent float64) string {
	sort.SliceStable(alerts, func(i, j int) bool {
		left := math.Abs(alerts[i].DistancePercent)
		right := math.Abs(alerts[j].DistancePercent)
		if left == right {
			if alerts[i].Stock.Ticker == alerts[j].Stock.Ticker {
				return alerts[i].Period < alerts[j].Period
			}
			return alerts[i].Stock.Ticker < alerts[j].Stock.Ticker
		}
		return left < right
	})

	var sb strings.Builder
	sb.WriteString(`<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<style>
  body { font-family: Arial, sans-serif; max-width: 920px; margin: 0 auto; padding: 20px; background: #f5f5f5; color: #24303d; }
  h2 { color: #333; border-bottom: 2px solid #2d8f6f; padding-bottom: 8px; }
  table { width: 100%; border-collapse: collapse; background: white; border-radius: 8px; overflow: hidden; box-shadow: 0 1px 4px rgba(0,0,0,0.1); }
  th { background: #17202a; color: white; padding: 10px 12px; text-align: left; font-size: 13px; }
  td { padding: 10px 12px; border-bottom: 1px solid #eee; font-size: 14px; vertical-align: top; }
  tr:last-child td { border-bottom: none; }
  .ticker { font-weight: bold; white-space: nowrap; }
  .category { color:#777; font-size:12px; }
  .number { text-align: right; white-space: nowrap; }
  .touch { color: #2d8f6f; font-weight: bold; }
  .near { color: #9b6a1d; font-weight: bold; }
  .above { color: #27ae60; }
  .below { color: #e74c3c; }
  .muted { color: #777; font-size: 12px; }
  .footer { margin-top: 16px; font-size: 12px; color: #999; }
</style>
</head>
<body>
`)
	sb.WriteString(fmt.Sprintf("<h2>EMA Proximity Alerts (%s) — %s</h2>\n", strings.ToUpper(timeframe.String()), time.Now().Format("02/01/2006")))
	sb.WriteString(fmt.Sprintf("<p class=\"muted\">Triggered when the latest candle touches EMA50/100/200 or closes within %.2f%% of it.</p>\n", thresholdPercent))
	sb.WriteString("<table>\n")
	sb.WriteString("  <tr><th>Stock</th><th>EMA</th><th>Status</th><th>Close</th><th>EMA value</th><th>Distance</th><th>Latest range</th></tr>\n")
	for _, alert := range alerts {
		statusClass := "near"
		status := "near"
		if alert.Touched {
			statusClass = "touch"
			status = "touch"
		}
		distanceClass := "above"
		if alert.DistancePercent < 0 {
			distanceClass = "below"
		}
		sb.WriteString(fmt.Sprintf(
			`  <tr>
    <td><span class="ticker">%s</span><br><span class="muted">%s</span><br><span class="category">%s</span></td>
    <td>EMA%d</td>
    <td class="%s">%s</td>
    <td class="number">%.2f</td>
    <td class="number">%.2f</td>
    <td class="number %s">%+.2f%%</td>
    <td class="number">%.2f → %.2f</td>
  </tr>
`,
			alert.Stock.Ticker,
			alert.Stock.Name,
			alert.Stock.Category,
			alert.Period,
			statusClass,
			status,
			alert.LastClose,
			alert.EMA,
			distanceClass,
			alert.DistancePercent,
			alert.LastLow,
			alert.LastHigh,
		))
	}
	sb.WriteString("</table>\n")
	sb.WriteString(`<p class="footer">Generated by stock-checker using Yahoo chart data.</p>`)
	sb.WriteString("</body>\n</html>")
	return sb.String()
}
