package divergencealerts

import (
	"fmt"
	"sort"
	"strings"
	"time"
)

func GenerateReport(alerts []Alert) string {
	sort.SliceStable(alerts, func(i, j int) bool {
		if alerts[i].Divergence.Kind == alerts[j].Divergence.Kind {
			return alerts[i].Stock.Ticker < alerts[j].Stock.Ticker
		}
		return alerts[i].Divergence.Kind == "bearish"
	})

	var sb strings.Builder
	sb.WriteString(`<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<style>
  body { font-family: Arial, sans-serif; max-width: 900px; margin: 0 auto; padding: 20px; background: #f5f5f5; color: #24303d; }
  h2 { color: #333; border-bottom: 2px solid #4a90e2; padding-bottom: 8px; }
  table { width: 100%; border-collapse: collapse; background: white; border-radius: 8px; overflow: hidden; box-shadow: 0 1px 4px rgba(0,0,0,0.1); }
  th { background: #17202a; color: white; padding: 10px 12px; text-align: left; font-size: 13px; }
  td { padding: 10px 12px; border-bottom: 1px solid #eee; font-size: 14px; vertical-align: top; }
  tr:last-child td { border-bottom: none; }
  .ticker { font-weight: bold; white-space: nowrap; }
  .category { color:#777; font-size:12px; }
  .number { text-align: right; white-space: nowrap; }
  .bearish { color: #e74c3c; font-weight: bold; }
  .bullish { color: #27ae60; font-weight: bold; }
  .muted { color: #777; font-size: 12px; }
  .footer { margin-top: 16px; font-size: 12px; color: #999; }
</style>
</head>
<body>
`)
	sb.WriteString(fmt.Sprintf("<h2>RSI Divergence Alerts — %s</h2>\n", time.Now().Format("02/01/2006")))
	sb.WriteString("<table>\n")
	sb.WriteString("  <tr><th>Stock</th><th>Signal</th><th>Pivot dates</th><th>Price move</th><th>RSI move</th><th>Last close</th></tr>\n")
	for _, alert := range alerts {
		div := alert.Divergence
		kindClass := div.Kind
		kindLabel := strings.ToUpper(div.Kind)
		sb.WriteString(fmt.Sprintf(
			`  <tr>
    <td><span class="ticker">%s</span><br><span class="muted">%s</span><br><span class="category">%s</span></td>
    <td class="%s">%s divergence</td>
    <td>%s → %s</td>
    <td class="number">%.2f → %.2f</td>
    <td class="number">%.1f → %.1f</td>
    <td class="number">%.2f</td>
  </tr>
`,
			alert.Stock.Ticker,
			alert.Stock.Name,
			alert.Stock.Category,
			kindClass,
			kindLabel,
			formatDate(div.FromTime),
			formatDate(div.ToTime),
			div.FromPrice,
			div.ToPrice,
			div.FromRSI,
			div.ToRSI,
			alert.LastClose,
		))
	}
	sb.WriteString("</table>\n")
	sb.WriteString(`<p class="footer">Generated by stock-checker using the stock-portfolio chart engine.</p>`)
	sb.WriteString("</body>\n</html>")
	return sb.String()
}

func EmailSubject(alerts []Alert) string {
	if len(alerts) == 0 {
		return ""
	}
	parts := make([]string, 0, len(alerts))
	for _, alert := range alerts {
		parts = append(parts, fmt.Sprintf("%s %s", alert.Stock.Ticker, alert.Divergence.Kind))
	}
	if len(parts) > 6 {
		parts = append(parts[:6], fmt.Sprintf("+%d more", len(parts)-6))
	}
	return fmt.Sprintf("RSI Divergence Alert: %s", strings.Join(parts, ", "))
}

func formatDate(ts int64) string {
	if ts <= 0 {
		return ""
	}
	return time.Unix(ts, 0).Format("02 Jan 2006")
}
